### ISSUE TITLE
请问模型实现会开源吗？

### ISSUE THREAD

**Issue by yasong** [binaryai/CodeCMR#1]
请问论文所提方法的实现代码后面会开源吗？

**Comment by nforest** [comment]
您好，模型代码目前没有开源计划，但模型能力会通过[SDK](https://github.com/binaryai/sdk)对外提供试用。

另外，通过科研合作，实习交流等形式可以获取数据、模型等内部资源，如有兴趣可以联系: KeenSecurityLab#tencent.com
