### ISSUE TITLE
What does integer token and integer number represent?

### ISSUE THREAD

**Issue by xunge** [binaryai/CodeCMR#2]
I am confused about `integer token` and `integer number` in the paper `3.3 Code literal features`. Can you explain in detail or give an example? Thanks.

**Comment by zepingyu0512** [comment]
> I am confused about `integer token` and `integer number` in the paper `3.3 Code literal features`. Can you explain in detail or give an example? Thanks.

Assuming the integer vocab has five tokens 1, 2, 3, 4, 5. 

Example: [2, 3, 4].
Integer token: [2, 3, 4]. 
Integer number: [2.0, 3.0, 4.0].

The integer tokens could be seen as word tokens, which will be computed into embeddings.
The integer number scores work in LSTM.

**Comment by xunge** [comment]
Thank you for your reply!
