### ISSUE TITLE
dataset misses source code 

### ISSUE THREAD

**Issue by island255** [binaryai/CodeCMR#3]
The description of the dataset writes:

_Each dataset has 33 columns, the first column is the source code, the other columns are the corresponding binary code on 32 combinations of different compilers (gcc/clang), different platforms (x86/x64/arm/arm64) and different optimizations (O0/O1/O2/O3)._

However, the released dataset, which can be download from google cloud, seems only to have 32 binaries but no source code.

Without source code, follow-up works are hard to be carried out and compared.

Please upload the source code to help this dataset complete if possible.

**Comment by zepingyu0512** [comment]
> The description of the dataset writes:
> 
> _Each dataset has 33 columns, the first column is the source code, the other columns are the corresponding binary code on 32 combinations of different compilers (gcc/clang), different platforms (x86/x64/arm/arm64) and different optimizations (O0/O1/O2/O3)._
> 
> However, the released dataset, which can be download from google cloud, seems only to have 32 binaries but no source code.
> 
> Without source code, follow-up works are hard to be carried out and compared.
> 
> Please upload the source code to help this dataset complete if possible.

Hello, corressponding source code is in the .pkl files.
How to open:

import pandas as pd
df = pd.read_pickle('test.pkl')
sample = df.iloc[0]
src = sample['c_label']

**Comment by island255** [comment]
Get it, thanks.

**Comment by island255** [comment]
I have scanned the source code in the .pkl file. Every source code seems to be a function without context. So I wonder how to compile them into binaries? And I also wonder how you collect them and where they are from? 

If you can open-source the complete version of this function to make compile them possible. I will be very grateful.

**Comment by nforest** [comment]
> I have scanned the source code in the .pkl file. Every source code seems to be a function without context. So I wonder how to compile them into binaries? And I also wonder how you collect them and where they are from?
> 
> If you can open-source the complete version of this function to make compile them possible. I will be very grateful.

Actually, we compiled lots of open-source projects into binaries and split the source/binary files into the corresponding function-level pairs.

We don't have a timeline to open-source this part of our work. However, there are no magic tricks inside, just normal source compilation and preprocessing.

**Comment by island255** [comment]
Actually, we are doing a similar job on source2binary code matching. But our method needs the full file of source code, as the source code of a single function cannot be analyzed. So can you open-source the full file of source code or send the source code to me? It will be beneficial to carry out a comparison experiment.

**Comment by nforest** [comment]
> Actually, we are doing a similar job on source2binary code matching. But our method needs the full file of source code, as the source code of a single function cannot be analyzed. So can you open-source the full file of source code or send the source code to me? It will be beneficial to carry out a comparison experiment.

In our experiment, all the source code are from the packages in famous linux distributions, such as http://mirrors.ustc.edu.cn/debian/ .

**Comment by island255** [comment]
Thanks.

**Comment by lucky-nolby** [comment]
> 

How to match function level source code with binary one by one? Is it by function name? I look forward to your reply.
